# Generated by Django 2.2.8 on 2020-04-15 19:19

import datetime
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uit.pbs_script


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tethys_compute', '0001_initial_30'),
    ]

    operations = [
        migrations.CreateModel(
            name='UitPlusJob',
            fields=[
                ('tethysjob_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tethys_compute.TethysJob')),
                ('job_id', models.CharField(max_length=1024, null=True)),
                ('archive_input_files', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2048, null=True), null=True, size=None)),
                ('home_input_files', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2048, null=True), null=True, size=None)),
                ('transfer_input_files', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2048, null=True), null=True, size=None)),
                ('project_id', models.CharField(max_length=1024)),
                ('num_nodes', models.IntegerField(default=1)),
                ('processes_per_node', models.IntegerField(default=1)),
                ('max_time', models.DurationField()),
                ('queue', models.CharField(default='debug', max_length=100)),
                ('node_type', models.CharField(choices=[('transfer', 'transfer'), ('compute', 'compute'), ('bigmem', 'bigmem'), ('gpu', 'gpu'), ('knl', 'knl')], default='compute', max_length=10)),
                ('system', models.CharField(choices=[('jim', 'jim'), ('onyx', 'onyx')], default='onyx', max_length=10)),
                ('execution_block', models.TextField()),
                ('archive_output_files', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2048, null=True), null=True, size=None)),
                ('home_output_files', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2048, null=True), null=True, size=None)),
                ('intermediate_transfer_interval', models.IntegerField(default=0)),
                ('last_intermediate_transfer', models.DateTimeField(default=django.utils.timezone.now)),
                ('max_cleanup_time', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('transfer_intermediate_files', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2048, null=True), null=True, size=None)),
                ('transfer_job_script', models.BooleanField(default=True)),
                ('transfer_output_files', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2048, null=True), null=True, size=None)),
                ('_modules', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('_optional_directives', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2048, null=True), size=None)),
                ('_process_intermediate_results_function', models.CharField(max_length=1024, null=True)),
                ('_remote_workspace', models.TextField(blank=True)),
                ('_remote_workspace_id', models.CharField(max_length=100)),
                ('_environment_variables', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('_array_indices', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
            ],
            bases=(uit.pbs_script.PbsScript, 'tethys_compute.tethysjob'),
        ),
    ]
