# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-28 00:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='UitPlusJob',
            fields=[
                ('tethysjob_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tethys_compute.TethysJob')),
                ('job_name', models.CharField(max_length=1024, unique=True)),
                ('project_id', models.CharField(max_length=1024)),
                ('num_nodes', models.IntegerField()),
                ('processes_per_node', models.IntegerField()),
                ('max_time', models.DurationField()),
                ('queue', models.CharField(default='debug', max_length=100)),
                ('node_type', models.CharField(choices=[('compute', 'compute'), ('gpu', 'gpu'), ('bigmem', 'bigmem')], default='compute', max_length=10)),
                ('system', models.CharField(choices=[('topaz', 'topaz'), ('onyx', 'onyx')], default='topaz', max_length=10)),
                ('_optional_directives', models.CharField(max_length=2048, null=True)),
                ('_modules', models.CharField(max_length=1024, null=True)),
                ('job_script', models.CharField(max_length=2048)),
                ('transfer_job_script', models.BooleanField(default=True)),
                ('transfer_input_files', models.CharField(max_length=1024, null=True)),
                ('archive_input_files', models.CharField(max_length=1024, null=True)),
                ('home_input_files', models.CharField(max_length=1024, null=True)),
                ('transfer_output_files', models.CharField(max_length=1024, null=True)),
                ('archive_output_files', models.CharField(max_length=1024, null=True)),
                ('home_output_files', models.CharField(max_length=1024, null=True)),
                ('job_id', models.CharField(max_length=1024, null=True)),
                ('_remote_workspace', models.CharField(blank=True, max_length=1024)),
            ],
            bases=('tethys_compute.tethysjob',),
        ),
    ]
