# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-17 21:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UitPlusJob',
            fields=[
                ('tethysjob_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tethys_compute.TethysJob')),
                ('project_id', models.CharField(max_length=1024)),
                ('num_nodes', models.IntegerField(default=1)),
                ('processes_per_node', models.IntegerField(default=1)),
                ('max_time', models.DurationField()),
                ('queue', models.CharField(default='debug', max_length=100)),
                ('node_type', models.CharField(choices=[('compute', 'compute'), ('gpu', 'gpu'), ('bigmem', 'bigmem')], default='compute', max_length=10)),
                ('system', models.CharField(choices=[('topaz', 'topaz'), ('onyx', 'onyx')], default='topaz', max_length=10)),
                ('_optional_directives', picklefield.fields.PickledObjectField(default=list, editable=False)),
                ('_modules', picklefield.fields.PickledObjectField(default=dict, editable=False)),
                ('job_script', models.TextField()),
                ('transfer_job_script', models.BooleanField(default=True)),
                ('transfer_input_files', picklefield.fields.PickledObjectField(default=list, editable=False)),
                ('archive_input_files', picklefield.fields.PickledObjectField(default=list, editable=False)),
                ('home_input_files', picklefield.fields.PickledObjectField(default=list, editable=False)),
                ('transfer_output_files', picklefield.fields.PickledObjectField(default=list, editable=False)),
                ('archive_output_files', picklefield.fields.PickledObjectField(default=list, editable=False)),
                ('home_output_files', picklefield.fields.PickledObjectField(default=list, editable=False)),
                ('job_id', models.CharField(max_length=1024, null=True)),
                ('_remote_workspace', models.TextField(blank=True)),
                ('_remote_workspace_id', models.CharField(max_length=100)),
                ('max_cleanup_time', models.DurationField(default=datetime.timedelta(0, 3600))),
            ],
            bases=('tethys_compute.tethysjob',),
        ),
    ]
