# Generated by Django 3.2.16 on 2023-03-10 21:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import uit.pbs_script


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tethys_compute", "0001_initial_41"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UitPlusJob",
            fields=[
                (
                    "tethysjob_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tethys_compute.tethysjob",
                    ),
                ),
                ("job_id", models.CharField(max_length=1024, null=True)),
                (
                    "archive_input_files",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "home_input_files",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "transfer_input_files",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("_remote_workspace", models.TextField(blank=True)),
                ("_remote_workspace_id", models.CharField(max_length=100)),
                ("qstat", models.JSONField(default=dict, null=True)),
                ("archived", models.BooleanField(default=False)),
                ("project_id", models.CharField(max_length=1024)),
                ("num_nodes", models.IntegerField(default=1)),
                ("processes_per_node", models.IntegerField(default=1)),
                ("_max_time", models.DurationField()),
                ("queue", models.CharField(default="debug", max_length=100)),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("bigmem", "bigmem"),
                            ("compute", "compute"),
                            ("gpu", "gpu"),
                            ("knl", "knl"),
                            ("transfer", "transfer"),
                        ],
                        default="compute",
                        max_length=10,
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        choices=[
                            ("jim", "jim"),
                            ("mustang", "mustang"),
                            ("narwhal", "narwhal"),
                            ("onyx", "onyx"),
                        ],
                        default="onyx",
                        max_length=10,
                    ),
                ),
                ("execution_block", models.TextField()),
                ("_modules", models.JSONField(default=dict, null=True)),
                ("_module_use", models.JSONField(default=dict, null=True)),
                (
                    "_optional_directives",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("_environment_variables", models.JSONField(default=dict, null=True)),
                (
                    "_array_indices",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "archive_output_files",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "home_output_files",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("intermediate_transfer_interval", models.IntegerField(default=0)),
                (
                    "last_intermediate_transfer",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "max_cleanup_time",
                    models.DurationField(default=datetime.timedelta(seconds=3600)),
                ),
                (
                    "transfer_intermediate_files",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("transfer_job_script", models.BooleanField(default=True)),
                (
                    "transfer_output_files",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("custom_logs", models.JSONField(default=dict)),
                (
                    "_process_intermediate_results_function",
                    models.CharField(max_length=1024, null=True),
                ),
            ],
            bases=(uit.pbs_script.PbsScript, "tethys_compute.tethysjob"),
        ),
        migrations.CreateModel(
            name="EnvironmentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("hpc_system", models.CharField(max_length=64)),
                ("software", models.CharField(max_length=1024, null=True)),
                ("email", models.CharField(max_length=1024, null=True)),
                ("environment_variables", models.CharField(max_length=2048, null=True)),
                ("modules", models.JSONField(default=dict, null=True)),
                ("last_used", models.DateTimeField(auto_now_add=True)),
                ("user_default", models.BooleanField(default=False)),
                (
                    "default_for_versions",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
