# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-29 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('uit_plus_job', '0001_initial'), ('uit_plus_job', '0002_auto_20181128_2150')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UitPlusJob',
            fields=[
                ('tethysjob_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tethys_compute.TethysJob')),
                ('project_id', models.CharField(max_length=1024)),
                ('num_nodes', models.IntegerField(default=1)),
                ('processes_per_node', models.IntegerField(default=1)),
                ('max_time', models.DurationField()),
                ('queue', models.CharField(default='debug', max_length=100)),
                ('node_type', models.CharField(choices=[('compute', 'compute'), ('gpu', 'gpu'), ('bigmem', 'bigmem')], default='compute', max_length=10)),
                ('system', models.CharField(choices=[('topaz', 'topaz'), ('onyx', 'onyx')], default='topaz', max_length=10)),
                ('_optional_directives', models.TextField(null=True)),
                ('_modules', models.TextField(null=True)),
                ('job_script', models.TextField()),
                ('transfer_job_script', models.BooleanField(default=True)),
                ('transfer_input_files', models.TextField(null=True)),
                ('archive_input_files', models.TextField(null=True)),
                ('home_input_files', models.TextField(null=True)),
                ('transfer_output_files', models.TextField(null=True)),
                ('archive_output_files', models.TextField(null=True)),
                ('home_output_files', models.TextField(null=True)),
                ('job_id', models.CharField(max_length=1024, null=True)),
                ('_remote_workspace', models.TextField(blank=True)),
            ],
            bases=('tethys_compute.tethysjob',),
        ),
    ]
