# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-28 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uit_plus_job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uitplusjob',
            name='job_name',
        ),
        migrations.AlterField(
            model_name='uitplusjob',
            name='_modules',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='uitplusjob',
            name='_optional_directives',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='uitplusjob',
            name='_remote_workspace',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='uitplusjob',
            name='archive_input_files',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='uitplusjob',
            name='archive_output_files',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='uitplusjob',
            name='home_input_files',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='uitplusjob',
            name='home_output_files',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='uitplusjob',
            name='job_script',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='uitplusjob',
            name='num_nodes',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='uitplusjob',
            name='processes_per_node',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='uitplusjob',
            name='transfer_input_files',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='uitplusjob',
            name='transfer_output_files',
            field=models.TextField(null=True),
        ),
    ]
