# Generated by Django 5.1.4 on 2025-02-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uit_plus_job", "0001_initial_41"),
    ]

    operations = [
        migrations.AddField(
            model_name="uitplusjob",
            name="_base_dir",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="uitplusjob",
            name="node_type",
            field=models.CharField(default="compute", max_length=10),
        ),
        migrations.AlterField(
            model_name="uitplusjob",
            name="system",
            field=models.CharField(max_length=10),
        ),
    ]
