# Generated by Django 2.2.14 on 2020-10-26 22:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uit_plus_job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uitplusjob',
            name='custom_logs',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='uitplusjob',
            name='node_type',
            field=models.CharField(choices=[('gpu', 'gpu'), ('compute', 'compute'), ('transfer', 'transfer'), ('bigmem', 'bigmem'), ('knl', 'knl')], default='compute', max_length=10),
        ),
    ]
