# Generated by Django 2.2.8 on 2020-03-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uit_plus_job', '0001_initial_migration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uitplusjob',
            old_name='job_script',
            new_name='execution_block',
        ),
        migrations.AlterField(
            model_name='uitplusjob',
            name='node_type',
            field=models.CharField(choices=[('bigmem', 'bigmem'), ('gpu', 'gpu'), ('compute', 'compute'), ('knl', 'knl'), ('transfer', 'transfer')], default='compute', max_length=10),
        ),
        migrations.AlterField(
            model_name='uitplusjob',
            name='system',
            field=models.CharField(choices=[('jim', 'jim'), ('onyx', 'onyx')], default='onyx', max_length=10),
        ),
    ]
