# Generated by Django 2.2.14 on 2020-11-04 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uit_plus_job', '0002_custom_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('hpc_system', models.CharField(max_length=64)),
                ('environment_variables', models.CharField(max_length=1024)),
                ('modules', models.CharField(max_length=1024)),
                ('last_used', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
