# Generated by Django 2.2.14 on 2021-01-26 23:36

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uit_plus_job', '0002_custom_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='uitplusjob',
            name='_module_use',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='uitplusjob',
            name='qstat',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.CreateModel(
            name='EnvironmentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('hpc_system', models.CharField(max_length=64)),
                ('environment_variables', models.CharField(max_length=1024)),
                ('modules', models.CharField(max_length=1024)),
                ('last_used', models.DateTimeField(auto_now_add=True)),
                ('user_default', models.BooleanField(default=False)),
                ('default_for_versions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), default=list, null=True, size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
