# Generated by Django 2.2.14 on 2021-02-18 13:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uit_plus_job', '0003_environment_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentprofile',
            name='email',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='environmentprofile',
            name='environment_variables',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='environmentprofile',
            name='modules',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
