# Generated by Django 2.2.5 on 2021-01-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uit_plus_job', '0003_environmentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentprofile',
            name='default_for_versions',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='environmentprofile',
            name='user_default',
            field=models.BooleanField(default=False),
        ),
    ]
