# Generated by Django 2.2.14 on 2021-03-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uit_plus_job', '0004_auto_20210218_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentprofile',
            name='software',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
