# Generated by Django 2.2.5 on 2021-01-05 16:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uit_plus_job', '0004_auto_20210104_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentprofile',
            name='default_for_versions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), default=list, null=True, size=None),
        ),
    ]
