# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-29 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uit_plus_job', '0004_auto_20181129_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='uitplusjob',
            name='_remote_workspace_id',
            field=models.CharField(default='8594e40a-c608-4d18-8060-8947ab4c1657', max_length=64),
        ),
    ]
