# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-29 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uit_plus_job', '0005_uitplusjob__remote_workspace_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uitplusjob',
            name='_remote_workspace_id',
            field=models.CharField(default='7d092229-a356-46de-b7b2-e5a697b9484b', max_length=64),
        ),
    ]
