# Generated by Django 2.2.14 on 2021-06-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uit_plus_job', '0005_environmentprofile_software'),
    ]

    operations = [
        migrations.AddField(
            model_name='uitplusjob',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
