# Generated by Django 2.2.14 on 2022-02-14 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uit_plus_job', '0006_uitplusjob_archived'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uitplusjob',
            old_name='max_time',
            new_name='_max_time',
        ),
    ]
