# Generated by Django 3.2.16 on 2023-03-10 16:57

from functools import partial
from django.db import migrations, models

db_dumps = {}


def get_model_objects(apps, schema_editor, app, model):
    Model = apps.get_model(app, model)
    db_alias = schema_editor.connection.alias
    return Model.objects.using(db_alias)


def dump_db_field(apps, schema_editor, app, model, field, id_field='id'):
    objects = get_model_objects(apps, schema_editor, app, model)
    field_dump = {}
    db_dumps[field] = field_dump
    for object in objects.all():
        field_dump[getattr(object, id_field)] = getattr(object, field)


def load_db_field(apps, schema_editor, app, model, field, id_field='id'):
    objects = get_model_objects(apps, schema_editor, app, model)
    field_dump = db_dumps.get(field)
    for id, value in field_dump.items():
        object = objects.get(**{id_field: id})
        setattr(object, field, value)
        object.save()


def get_dump_load_funcs(app, model, field, id_field='id'):
    dump_func = partial(dump_db_field, app=app, model=model, field=field, id_field=id_field)
    load_func = partial(load_db_field, app=app, model=model, field=field, id_field=id_field)
    return dump_func, load_func


dict_fields = [
    dict(
        model_name='environmentprofile',
        name='modules',
    ),
    dict(
        model_name='uitplusjob',
        name='qstat',
    ),
    dict(
        model_name='uitplusjob',
        name='_modules',
    ),
    dict(
        model_name='uitplusjob',
        name='_module_use',
    ),
    dict(
        model_name='uitplusjob',
        name='_environment_variables',
    ),
    dict(
        model_name='uitplusjob',
        name='custom_logs',
        null=False,
    ),

]

array_fields = [
    dict(
        model_name='environmentprofile',
        name='default_for_versions',
    ),
    dict(
        model_name='uitplusjob',
        name='archive_input_files',
    ),
    dict(
        model_name='uitplusjob',
        name='home_input_files',
    ),
    dict(
        model_name='uitplusjob',
        name='transfer_input_files',
    ),
    dict(
        model_name='uitplusjob',
        name='_optional_directives',
    ),
    dict(
        model_name='uitplusjob',
        name='_array_indices',
    ),
    dict(
        model_name='uitplusjob',
        name='archive_output_files',
    ),
    dict(
        model_name='uitplusjob',
        name='home_output_files',
    ),
    dict(
        model_name='uitplusjob',
        name='transfer_intermediate_files',
    ),
    dict(
        model_name='uitplusjob',
        name='transfer_output_files',
    ),
]

alter_json_filed_operations = []
app = 'uit_plus_job'


def add_json_migration_operations(d, field_kwargs):
    dump_func, load_func = get_dump_load_funcs(
        app=app,
        model=d['model_name'],
        field=d['name'],
    )
    kwargs = dict(
        model_name=d['model_name'],
        name=d['name'],
    )
    field_kwargs['null'] = d.get('null', True)
    alter_json_filed_operations.extend(
        [
            migrations.RunPython(dump_func, load_func),
            migrations.RemoveField(**kwargs),
            migrations.AddField(
                **kwargs,
                field=models.JSONField(**field_kwargs),
            ),
            migrations.RunPython(load_func, dump_func),

        ]
    )


for d in dict_fields:
    add_json_migration_operations(d, {'default': dict})
for d in array_fields:
    add_json_migration_operations(d, {'blank': True, 'default': list})


class Migration(migrations.Migration):

    dependencies = [
        ('uit_plus_job', '0007_auto_20220214_1923'),
    ]

    operations = alter_json_filed_operations
