# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-30 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uit_plus_job', '0007_auto_20181129_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uitplusjob',
            name='_remote_workspace_id',
            field=models.CharField(default='b046d548-f8a6-4629-8d9a-8554498d5b73', max_length=64),
        ),
    ]
