# Generated by Django 3.2.16 on 2023-03-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uit_plus_job', '0008_auto_20230310_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='uitplusjob',
            name='system',
            field=models.CharField(choices=[('jim', 'jim'), ('narwhal', 'narwhal'), ('onyx', 'onyx')], default='onyx', max_length=10),
        ),
    ]
