# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-08 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uit_plus_job', '0008_auto_20181130_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uitplusjob',
            name='_remote_workspace_id',
            field=models.CharField(max_length=100),
        ),
    ]
