# Generated by Django 3.2.16 on 2023-03-10 16:57

from functools import partial
from django.db import migrations, models


array_fields = [
    dict(
        model_name='environmentprofile',
        name='default_for_versions',
    ),
    dict(
        model_name='uitplusjob',
        name='archive_input_files',
    ),
    dict(
        model_name='uitplusjob',
        name='home_input_files',
    ),
    dict(
        model_name='uitplusjob',
        name='transfer_input_files',
    ),
    dict(
        model_name='uitplusjob',
        name='_optional_directives',
    ),
    dict(
        model_name='uitplusjob',
        name='_array_indices',
    ),
    dict(
        model_name='uitplusjob',
        name='archive_output_files',
    ),
    dict(
        model_name='uitplusjob',
        name='home_output_files',
    ),
    dict(
        model_name='uitplusjob',
        name='transfer_intermediate_files',
    ),
    dict(
        model_name='uitplusjob',
        name='transfer_output_files',
    ),
]

alter_json_filed_operations = []
app = 'uit_plus_job'


def add_json_migration_operations(d, field_kwargs):
    kwargs = dict(
        model_name=d['model_name'],
        name=d['name'],
    )
    field_kwargs['null'] = d.get('null', True)
    alter_json_filed_operations.extend(
        [
            migrations.RemoveField(**kwargs),
            migrations.AddField(
                **kwargs,
                field=models.JSONField(**field_kwargs),
            ),

        ]
    )


for d in array_fields:
    add_json_migration_operations(d, {'blank': True, 'default': list})


class Migration(migrations.Migration):

    dependencies = [
        ('uit_plus_job', '0008_auto_20230414_1548'),
    ]

    operations = alter_json_filed_operations
